# permissions for end users to edit pathfinders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pathfinder-editor-role
rules:
- apiGroups:
  - xmbsmdsj.com
  resources:
  - pathfinders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - xmbsmdsj.com
  resources:
  - pathfinders/status
  verbs:
  - get
