# permissions for end users to view pathfinders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pathfinder-viewer-role
rules:
- apiGroups:
  - xmbsmdsj.com
  resources:
  - pathfinders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - xmbsmdsj.com
  resources:
  - pathfinders/status
  verbs:
  - get
