apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-web
  template:
    metadata:
      labels:
        app: flask-web
    spec:
      containers:
      - name: flask-web
        image: digitalocean/flask-helloworld
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
---

apiVersion: v1
kind: Service
metadata:
  annotations:
    XM-PathFinder-Region: DEFAULT
    XM-PathFinder-Service: Activated
    XM-PathFinder-ServiceName: hello-world
  name: flask-service
spec:
  selector:
    app: flask-web
  ports:
  - port: 5000
    targetPort: 5000
